const companise = {
    "result": [
        {
            "empId": null,
            "code": "576201",
            "siteCode": "576201",
            "address": "泾岸村1区173号",
            "distance": "2.6443",
            "city": null,
            "latitude": "28.668401341141764",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "15919737871",
            "district": null,
            "name": "黄岩新前二部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.21416332203764"
        },
        {
            "empId": null,
            "code": "57635",
            "siteCode": "57635",
            "address": "新中路180号",
            "distance": "2.9892",
            "city": null,
            "latitude": "28.662353",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "0576-81122819",
            "district": null,
            "name": "黄岩新前分部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.220392"
        },
        {
            "empId": null,
            "code": "57629",
            "siteCode": "57629",
            "address": "坎头张10",
            "distance": "3.5521",
            "city": null,
            "latitude": "28.63400172",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "13058729188",
            "district": null,
            "name": "黄岩澄江",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.21558520"
        },
        {
            "empId": null,
            "code": "57642",
            "siteCode": "57642",
            "address": "惠民路8号",
            "distance": "3.8200",
            "city": null,
            "latitude": "28.62410212",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "15967045809",
            "district": null,
            "name": "黄岩北洋分部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.20149926"
        },
        {
            "empId": null,
            "code": "57634",
            "siteCode": "57634",
            "address": "惠民路8号",
            "distance": "4.4394",
            "city": null,
            "latitude": "28.67900831",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "18357000371",
            "district": null,
            "name": "黄岩城北二部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.22833741"
        },
        {
            "empId": null,
            "code": "57965",
            "siteCode": "57965",
            "address": "西城街道西洋郑小区4幢102",
            "distance": "4.5134",
            "city": null,
            "latitude": "28.67793978",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "18805764168",
            "district": null,
            "name": "黄岩淘宝九部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.23000237"
        },
        {
            "empId": null,
            "code": "57620",
            "siteCode": "57620",
            "address": "江口大闸路36号中通快递",
            "distance": "4.9176",
            "city": null,
            "latitude": "28.679033",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "18657199087",
            "district": null,
            "name": "黄岩",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.234073"
        },
        {
            "empId": null,
            "code": "57625",
            "siteCode": "57625",
            "address": "惠民路8号",
            "distance": "4.9363",
            "city": null,
            "latitude": "28.679156",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "13336737272",
            "district": null,
            "name": "黄岩城东一部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.234214"
        },
        {
            "empId": null,
            "code": "57624",
            "siteCode": "57624",
            "address": "惠民路8号",
            "distance": "5.1873",
            "city": null,
            "latitude": "28.67972265",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "0576-89603165",
            "district": null,
            "name": "黄岩市区四部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.23680311"
        },
        {
            "empId": null,
            "code": "57636",
            "siteCode": "57636",
            "address": "惠民路8号",
            "distance": "5.2783",
            "city": null,
            "latitude": "28.68118478",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "15988918005",
            "district": null,
            "name": "黄岩南城",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.23692106"
        },
        {
            "empId": null,
            "code": "57656",
            "siteCode": "57656",
            "address": "后庄工业区",
            "distance": "5.3752",
            "city": null,
            "latitude": "28.670911",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "13957624119",
            "district": null,
            "name": "黄岩城北三部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.243122"
        },
        {
            "empId": null,
            "code": "57632",
            "siteCode": "57632",
            "address": "兴东路166号",
            "distance": "5.5140",
            "city": null,
            "latitude": "28.66131063",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "15325767673",
            "district": null,
            "name": "黄岩模具城",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.24665181"
        },
        {
            "empId": null,
            "code": "57918",
            "siteCode": "57918",
            "address": "惠民路8号",
            "distance": "5.5190",
            "city": null,
            "latitude": "28.67872",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "0576-81101910",
            "district": null,
            "name": "黄岩市区五部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.241228"
        },
        {
            "empId": null,
            "code": "58390",
            "siteCode": "58390",
            "address": "惠民路8号",
            "distance": "5.6413",
            "city": null,
            "latitude": "28.64718416",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "13606827590",
            "district": null,
            "name": "黄岩城西二部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.24706753"
        },
        {
            "empId": null,
            "code": "58423",
            "siteCode": "58423",
            "address": "西城街道",
            "distance": "5.7260",
            "city": null,
            "latitude": "28.642095",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "15700083435",
            "district": null,
            "name": "黄岩市区七部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.246508"
        },
        {
            "empId": null,
            "code": "58123",
            "siteCode": "58123",
            "address": "西城街道耀达天玺（淘宝十部06-03）",
            "distance": "6.8192",
            "city": null,
            "latitude": "28.631155309112896",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "15067680407",
            "district": null,
            "name": "黄岩淘宝十部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.25370367633507"
        },
        {
            "empId": null,
            "code": "57633",
            "siteCode": "57633",
            "address": "大桥路649号",
            "distance": "7.0143",
            "city": null,
            "latitude": "28.67399",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "15168019496",
            "district": null,
            "name": "黄岩城北一部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.259591"
        },
        {
            "empId": null,
            "code": "58120",
            "siteCode": "58120",
            "address": "伍尚洋村",
            "distance": "7.0730",
            "city": null,
            "latitude": "28.68197879",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "15257699997",
            "district": null,
            "name": "黄岩头陀分部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.25703277"
        },
        {
            "empId": null,
            "code": "57621",
            "siteCode": "57621",
            "address": "惠民路8号",
            "distance": "7.1287",
            "city": null,
            "latitude": "28.65182947",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "13157655959",
            "district": null,
            "name": "黄岩市区一部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.26316550"
        },
        {
            "empId": null,
            "code": "57654",
            "siteCode": "57654",
            "address": "台州市黄岩区",
            "distance": "7.3370",
            "city": null,
            "latitude": "28.65497218",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "18657696835",
            "district": null,
            "name": "黄岩淘宝四部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.26550636"
        },
        {
            "empId": null,
            "code": "576203",
            "siteCode": "576203",
            "address": "九龙坊吾悦金街店",
            "distance": "7.5622",
            "city": null,
            "latitude": "28.65972699",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "17717407155",
            "district": null,
            "name": "黄岩城北五部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.26778731"
        },
        {
            "empId": null,
            "code": "58139",
            "siteCode": "58139",
            "address": "高丰中路36号",
            "distance": "8.7029",
            "city": null,
            "latitude": "28.591501",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "13173783877",
            "district": null,
            "name": "黄岩高桥二部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.239084"
        },
        {
            "empId": null,
            "code": "57626",
            "siteCode": "57626",
            "address": "惠民路8号",
            "distance": "8.8018",
            "city": null,
            "latitude": "28.65343389",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "17681682049",
            "district": null,
            "name": "黄岩城东二部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.28045281"
        },
        {
            "empId": null,
            "code": "57622",
            "siteCode": "57622",
            "address": "黄岩横街东路218号",
            "distance": "8.9714",
            "city": null,
            "latitude": "28.646528",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "18969622806",
            "district": null,
            "name": "黄岩市区二部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.281503"
        },
        {
            "empId": null,
            "code": "57623",
            "siteCode": "57623",
            "address": "黄椒路125号",
            "distance": "9.0015",
            "city": null,
            "latitude": "28.662442",
            "typeName": "网点",
            "serviceTime": null,
            "typeCode": "9",
            "province": null,
            "empCode": null,
            "phone": "15355699660",
            "district": null,
            "name": "黄岩市区三部",
            "businessPhone": null,
            "masterPhone": null,
            "longitude": "121.282394"
        }
    ],
    "message": "请求成功",
    "statusCode": "E0000",
    "status": true
}
var newCompanise = ''
companise.result.forEach((item) => {
    const {address,name,phone} = item
newCompanise+=address+' '
newCompanise+=name+' '
newCompanise+=phone
newCompanise+='\n'
})
console.log(newCompanise);

// "empId": null,
//             "code": "576201",
//             "siteCode": "576201",
//             "address": "泾岸村1区173号",
//             "distance": "2.6443",
//             "city": null,
//             "latitude": "28.668401341141764",
//             "typeName": "网点",
//             "serviceTime": null,
//             "typeCode": "9",
//             "province": null,
//             "empCode": null,
//             "phone": "15919737871",
//             "district": null,
//             "name": "黄岩新前二部",
//             "businessPhone": null,
//             "masterPhone": null,
//             "longitude": "121.21416332203764"